### ISSUE TITLE
Custom task execution

### ISSUE THREAD

**Issue by bmorton** [bmorton/deployster#5]
Allow tasks, such as `rake db:migrate`, to be run before a deploy.  This doesn't necessarily have to be part of the `POST /services/{service}/deploys` step, but it needs to be automatable for the case where something like Circle CI is handling the continuous delivery of a service and needs to optionally run tasks.

Thinking out loud about details of this feature:

* A version will need to be specified.
* Likely interested in the output of the task.
* The exit code of the task could determine the HTTP response code (so that CI tasks could halt on a failed task).  How do we do this if we're streaming the output of the task?
* Do we care about scheduling the task in the cluster with Fleet?  Should we just run it with Docker on the node that deployster is running on?

**Comment by bmorton** [comment]
My first pass at an implementation for this:

`POST /services/railsapp/tasks`

```json
{
    "task": {
        "command": "rake db:migrate",
        "version": "abc213"
    }
}
```

This will use a Docker client to execute something akin to: `docker run -ti mmmhm/railsapp:abc123 rake db:migrate`

First implementation will stream the logs from Docker straight to that HTTP request.  We'll still need to solve the HTTP status code/failure communication problem.

**Comment by bobbytables** [comment]
I would almost scope the tasks down so it's not *always* a docker command. For example, if you need to bounce a process, this would break down. A docker helper, on the other hand might make more sense.

Modifying your example:

```json
{
    "task": {
        "type": "docker",
        "command": "rake db:migrate",
        "version": "abc213"
    }
}
```

**Comment by bmorton** [comment]
In the CoreOS model, [everything is containerized](https://coreos.com/using-coreos/), so likely you wouldn't be bouncing a process or anything.  I think I'm okay with restricting this to Docker at the moment as an opinionated convention for running tasks.

Can you think of a good example where this would break down?

**Comment by bmorton** [comment]
I keep going back and forth between if this should be straight Docker or if it should be routed through Fleet.  I went the Docker route since it was simpler and it wasn't immediately obvious how to build a unit file for something that is meant to run once and be completed.

The drawback to using Docker directly instead of through Fleet is that the work can't be scheduled out to another node.  It has to be to the node that deployster is configured to hit.  This might change if CoreOS decides to ship Docker's Swarm stuff so that we can hit a single Docker endpoint, but swarm allows it to be scheduled and attached to another node.

**Comment by bmorton** [comment]
This has been completed in #14.  More discussion about design and tradeoffs in that pull request.
